### ISSUE TITLE
Chat render failing - causes Ceres container to crash

### ISSUE THREAD

**Issue by andymcblane** [Zibbp/Ceres#5]
Hello, nice tool. Thank you for creating. 

I am trying to manually archive a VOD - though seems to time out (so 500 return) and then the container dies 

![image](https://user-images.githubusercontent.com/3156198/166839155-f2618c24-af79-4616-b986-b019576e6eb1.png)

Any assistance would be appreciated! Thanks

**Comment by andymcblane** [comment]
![image](https://user-images.githubusercontent.com/3156198/166839849-0f097a38-83d9-4164-92da-557a1951b0ae.png)
hmmm... looks like the CLI is dying. Will dig further

**Comment by andymcblane** [comment]
oops, wrong code 

![image](https://user-images.githubusercontent.com/3156198/166845667-a702139b-f035-4267-844b-63ede1151154.png)

**Comment by Zibbp** [comment]
Hi, I tried rendering the VOD's chat and could not reproduce the issue. Some thoughts - 
- Is this the first VOD you've archived or have you successfully archived others? 
- Did you run out of storage space when the chat was rendering?

If you have the `/logs` directory mounted, can you upload the log files for the chat download and render for the VOD?

**Comment by andymcblane** [comment]
Hi Zibbp - thanks for the reply. 

* Yes this is the first VOD I'm attempting to run. 
* Space not an issue, 

Yes sorry, forgot there was a `logs` dir. 

Am trying to reproduce but hitting this now.

``root@Tower:/mnt/user/ceres/logs# ls
1474866561_chat_download.log  1474866561_video_download.log
root@Tower:/mnt/user/ceres/logs# cat 1474866561_chat_download.log 
[STATUS] - Downloading 2%
root@Tower:/mnt/user/ceres/logs# 
root@Tower:/mnt/user/ceres/logs# cat 1474866561_video_download.log 
Unhandled exception. System.AggregateException: One or more errors occurred. (Resource temporarily unavailable Resource temporarily unavailable)
 ---> System.Net.WebException: Resource temporarily unavailable Resource temporarily unavailable
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(IProgress`1 progress, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Program.DownloadVideo(Options inputOptions)
   at TwitchDownloaderCLI.Program.Main(String[] args)
Video download 1474866561 exited with code nullroot@Tower:/mnt/user/ceres/logs# ``

Looks like a networking issue potentially?

**Comment by Zibbp** [comment]
Looks like [TwitchDownloader](https://github.com/lay295/TwitchDownloader) is having connection issues downloading the video. I'm assuming the video download completed the first try? Maybe your internet is having issues? Could also take a look at the TwitchDownloader repo for similar issues if it isn't a connection issue. My knowledge with the TwitchDownloader application is limited.

Does the video continue to error after attempting again? It appears from the chat log that it was started and didn't fail. So is it only with the video download?

**Comment by andymcblane** [comment]
Yep I came to the same conclusions. All my issues so far point to that tool :P 

Had a brief look at the repo and source code but nothing stands out to me. I'll do some more tests and follow up here, 

Thanks

**Comment by Zibbp** [comment]
I see you're running Unraid from your logs, is the Unraid host x86 or ARM?

You could attempt downloading the TwitchDownloader CLI and running on the Unraid host (or a debian docker container) and try to manually downloading the VOD and see if there are any errors.

**Comment by andymcblane** [comment]
Yep x86 (i7 7700) 

Will give that a go 👍

**Comment by Zibbp** [comment]
I have not tried running Ceres on Unraid but I do run some other containers on Unraid and I don't suspect that Unraid is causing network issues but I could be wrong.

**Comment by andymcblane** [comment]
https://github.com/lay295/TwitchDownloader/issues/318

Issue occurs on the host also, in addition to an Ubuntu VM.

**Comment by andymcblane** [comment]
I got it working, not sure what happened...

Suspect chat render was failing due to insufficient space for Docker (download VOD, ffmpeg vod, render chat video etc). 

Thanks for help :)

**Comment by Zibbp** [comment]
The temporary downloading storage requirement can be quite high at times depending on the VOD downloading. It first needs to download the playlist chunks of the VOD (8K bittrate, 8 hours is 26GB) then it strings together the playlist chunks resulting in a temporary moment where both the chunks and mp4 file are present using 50+ GBs. Chat renders depending on the duration and number of messages could easily be 10GB.
